### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [kavinjindal/ObFile#2]
hello sir can i ask about something i have source code i want to protected him from thief and i will rent them for people and i want to be control at him like make him working by every ip never access with any one without make the ip access from me if try any other ip to using my code without make him access from me say can't access talk to owner

thank you i hope help me sir

**Comment by kavin-jindal** [comment]
Can u please elaborate
You want that no one accesses ur source code easily?

**Comment by VoipSip** [comment]
yes also my code is python lag he is for scanning not a backdoor or anything other but he is big code i will protect all files but i want to be control to not anyone using him without give him access from me

**Comment by kavin-jindal** [comment]
So its suggested to obfuscate the files to make it harder for them to reas,
you can use obfuscation tool of Obfile to make the code harder to read

**Comment by kavin-jindal** [comment]
Pls reply as i have to close the issue within next 72 hours

**Comment by VoipSip** [comment]
this Obfile  make me control at my script like create password for everyone will using my script or give access ip to him from me ?

**Comment by kavin-jindal** [comment]
Nope, actually its a compiler and obfuscator which can obfuscate ur files
and compile them, so what i suggest u in ur problem is that u can obfuscate
ur file so that it becomes hard for others to read and copy the code.

**Comment by VoipSip** [comment]
thank you very much for answer
